# Generated by Django 5.1.3 on 2024-11-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_published_date_book_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Published_date',
            new_name='published_date',
        ),
    ]
